// ============================================================================
// BuySel Web API - .NET 8 Minimal API Backend
// ============================================================================
//
// OVERVIEW:
// Backend API for the BuySel real estate application. Handles all data
// operations including properties, users, offers, conversations, and push
// notifications.
//
// ARCHITECTURE:
// - .NET 8 Minimal APIs (no controllers, uses endpoint routing)
// - Entity Framework Core with Azure SQL Database
// - JWT Bearer authentication (tokens generated by Next.js frontend)
// - Azure Blob Storage for photos (URLs stored in database)
//
// AUTHENTICATION FLOW:
// 1. User logs in via Google OAuth on Next.js frontend
// 2. Frontend generates JWT with user claims (lib/auth/jwt.ts)
// 3. JWT sent in Authorization header: "Bearer <token>"
// 4. This backend validates JWT using shared secret
//
// CONFIGURATION (appsettings.json or environment variables):
// - JWT_SECRET: Shared secret for HS256 signing (MUST match frontend)
// - JWT_ISSUER: Token issuer claim (default: "BuySell")
// - JWT_AUDIENCE: Token audience claim (default: "CharterTowers")
// - ConnectionStrings:DefaultConnection: Azure SQL connection string
// - GOOGLE_MAPS_API_KEY: For geocoding property addresses
// - APNS:*: Apple Push Notification Service credentials
//
// ENDPOINTS (see endpoint/*.cs for details):
// - /api/user: User management
// - /api/property: Property listings (CRUD, search, geocoding)
// - /api/propertyphoto: Property photos (Azure Blob)
// - /api/offer: Purchase offers and counter-offers
// - /api/offercondition: Offer conditions (finance, inspection)
// - /api/conversation: Chat threads between buyers/sellers
// - /api/message: Chat messages
// - /api/push: Push notification subscriptions
// - /api/audit: Admin audit logs
//
// DEPLOYMENT:
// - Azure App Service (buysel.azurewebsites.net)
// - Runs on port 5005 locally
// ============================================================================

using buyselwebapi.data;
using buyselwebapi.endpoint;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.RateLimiting;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using System.Text;
using System.Threading.RateLimiting;


var builder = WebApplication.CreateBuilder(args);

// ======================== SWAGGER ========================
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

// ======================== CORS ========================
// Allow requests from Next.js frontend (both local dev and production)
builder.Services.AddCors(options =>
{
    options.AddPolicy("NextJsPolicy", policy =>
    {
        policy.WithOrigins(
                "http://localhost:3000",
                "http://localhost:5005",
                "http://localhost:5000",
                "http://localhost:7188",
                "https://localhost:5005",
                "https://localhost:5000",
                "https://localhost:7188",
                "https://buysel-webapp.azurewebsites.net",
                "https://buysel.azurewebsites.net"
            )
            .AllowAnyHeader()
            .AllowAnyMethod()
            .AllowCredentials();
    });
});

// ======================== RATE LIMITING ========================
// Protects against brute force attacks and DDoS
// "auth": Stricter limits for login endpoints (10 req/min)
// "general": Standard API limits (60 req/min)
builder.Services.AddRateLimiter(options =>
{
    options.RejectionStatusCode = StatusCodes.Status429TooManyRequests;
    options.AddFixedWindowLimiter("auth", opt =>
    {
        opt.PermitLimit = 10;
        opt.Window = TimeSpan.FromMinutes(1);
        opt.QueueLimit = 0;
    });
    options.AddFixedWindowLimiter("general", opt =>
    {
        opt.PermitLimit = 60;
        opt.Window = TimeSpan.FromMinutes(1);
        opt.QueueLimit = 0;
    });
});

// ======================== HTTP CLIENTS ========================
// Named HTTP client for external API calls (Google Maps geocoding)
builder.Services.AddHttpClient("GoogleMaps", client =>
{
    client.BaseAddress = new Uri("https://maps.googleapis.com");
    client.Timeout = TimeSpan.FromSeconds(10);
});

// ======================== AUTHENTICATION ========================
// JWT Bearer authentication for API requests
// Tokens are generated by Next.js frontend (lib/auth/jwt.ts)
// IMPORTANT: JWT_SECRET must match between frontend and backend!
builder.Services.AddAuthorization();
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
.AddJwtBearer(o =>
{
    // Enforce HTTPS for token transmission in production
    o.RequireHttpsMetadata = !builder.Environment.IsDevelopment();

    // Use legacy JwtSecurityTokenHandler for Azure App Service compatibility
    // (Azure's default handler has issues with some JWT formats)
    o.SecurityTokenValidators.Clear();
    o.SecurityTokenValidators.Add(new System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler());

    // JWT configuration - reads from appsettings.json, then env vars, then defaults
    var jwtSecret = builder.Configuration["JWT_SECRET"] ?? Environment.GetEnvironmentVariable("JWT_SECRET") ?? "BuySellCharterTowers123456789012";
    var jwtIssuer = builder.Configuration["JWT_ISSUER"] ?? Environment.GetEnvironmentVariable("JWT_ISSUER") ?? "BuySell";
    var jwtAudience = builder.Configuration["JWT_AUDIENCE"] ?? Environment.GetEnvironmentVariable("JWT_AUDIENCE") ?? "CharterTowers";

    o.TokenValidationParameters = new TokenValidationParameters
    {
        IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(jwtSecret)),
        ValidIssuer = jwtIssuer,
        ValidAudience = jwtAudience,
        ValidateIssuerSigningKey = true,
        ValidateIssuer = true,
        ValidateAudience = true,
        ValidateLifetime = true,
        ClockSkew = TimeSpan.Zero
    };
    o.Events = new JwtBearerEvents
    {
        OnMessageReceived = context =>
        {
            var authHeader = context.Request.Headers["Authorization"].FirstOrDefault();
            Console.WriteLine($"Auth Header: {authHeader?.Substring(0, Math.Min(authHeader?.Length ?? 0, 80))}...");
            if (authHeader?.StartsWith("Bearer ") == true)
            {
                var token = authHeader.Substring(7);
                var parts = token.Split('.');
                Console.WriteLine($"Token parts: {parts.Length}");

                // Explicitly set the token to ensure the handler gets it correctly
                context.Token = token;

                if (parts.Length >= 2)
                {
                    try
                    {
                        var payload = System.Text.Encoding.UTF8.GetString(Convert.FromBase64String(parts[1].PadRight((parts[1].Length + 3) / 4 * 4, '=')));
                        Console.WriteLine($"Payload: {payload}");
                    }
                    catch (Exception ex) { Console.WriteLine($"Decode error: {ex.Message}"); }
                }
            }
            return Task.CompletedTask;
        },
        OnAuthenticationFailed = context =>
        {
            Console.WriteLine($"JWT Auth Failed: {context.Exception.GetType().Name}: {context.Exception.Message}");
            return Task.CompletedTask;
        },
        OnTokenValidated = context =>
        {
            Console.WriteLine($"JWT Token Validated for: {context.Principal?.Identity?.Name}");
            Console.WriteLine($"Claims: {string.Join(", ", context.Principal?.Claims.Select(c => c.Type + "=" + c.Value) ?? Array.Empty<string>())}");
            return Task.CompletedTask;
        }
    };
});

// ======================== DATABASE ========================
// Entity Framework Core with Azure SQL Database
// Connection string priority: appsettings.json > environment variable > default
var connectionString = builder.Configuration.GetConnectionString("DefaultConnection")
    ?? Environment.GetEnvironmentVariable("DB_CONNECTION_STRING")
    ?? "Server=buyselserver.database.windows.net,1433;Initial Catalog=buysel;Persist Security Info=False;User ID=buysel;Password=ABC1234!;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;";

builder.Services.AddDbContext<dbcontext>(options =>
    options.UseSqlServer(connectionString));

var app = builder.Build();

// ============================================================================
// MIDDLEWARE PIPELINE
// Order is critical! See ASP.NET Core middleware documentation.
// ============================================================================

// Swagger API documentation (currently enabled in all environments for testing)
// TODO: Restrict to development only in production: if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

// Security headers - protects against XSS, clickjacking, MIME sniffing
app.Use(async (context, next) =>
{
    context.Response.Headers.Append("X-Content-Type-Options", "nosniff");
    context.Response.Headers.Append("X-Frame-Options", "DENY");
    context.Response.Headers.Append("X-XSS-Protection", "1; mode=block");
    context.Response.Headers.Append("Referrer-Policy", "strict-origin-when-cross-origin");
    context.Response.Headers.Append("Permissions-Policy", "camera=(), microphone=(), geolocation=()");
    await next();
});

// #8 - Enforce HTTPS
app.UseHttpsRedirection();

// IMPORTANT: Order matters!
// 1. CORS must come before Authentication
app.UseCors("NextJsPolicy");

// #7 - Rate limiter middleware
app.UseRateLimiter();

// 2. Authentication must come before Authorization
app.UseAuthentication();

// 3. Authorization comes last
app.UseAuthorization();

// ============================================================================
// ENDPOINT ROUTING
// Each Map*Endpoints() registers a group of related endpoints.
// See endpoint/*.cs for individual endpoint implementations.
// ============================================================================

// Apply rate limiting to all endpoints by default
// TODO: Re-enable RequireAuthorization() for production:
// var api = app.MapGroup("").RequireAuthorization().RequireRateLimiting("general");
var api = app.MapGroup("").RequireRateLimiting("general");

// Core entities
api.MapPropertyEndpoints();      // /api/property - Property listings CRUD + search
api.MapPropertyPhotoEndpoints(); // /api/propertyphoto - Photo upload/management
api.MapUserEndpoints();          // /api/user - User management

// Communication
api.MapConversationEndpoints();  // /api/conversation - Chat threads
api.MapMessageEndpoints();       // /api/message - Chat messages
api.MapPushSubscriptionEndpoints(); // /api/push - Push notification subscriptions

// Offers & Documents
api.MapOfferEndpoints();         // /api/offer - Purchase offers
api.MapOfferConditionEndpoints(); // /api/offercondition - Offer conditions (finance, inspection)
api.MapOfferHistoryEndpoints();  // /api/offerhistory - Offer history/audit trail
api.MapPropertyBuyerDocEndpoints(); // /api/propertybuyerdoc - Document access requests

// Supporting features
api.MapUserPropertyFavEndpoints(); // /api/userpropertyfav - User favorites
api.MapBadgeEndpoints();         // /api/badge - User badges/achievements
api.MapAuditEndpoints();         // /api/audit - Admin audit logs

app.Run();
